FSM:
  _:
    Passive:
      id: 1
    FixStand:
      id: 2
    PushBox:
      id: 3
      type: PushBoxRL
  Passive:
    transitions:
      FixStand: LT + A.on_pressed
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions:
      Passive: LT + B.on_pressed
      PushBox: start.on_pressed
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5],
    ]
  PushBox:
    transitions:
      Passive: LT + B.on_pressed
    high_level_policy: config/exported/push_high_policy.onnx
    low_level_policy: config/exported/walk_low_level_policy.onnx
    push_box_obs_topic: rt/push_box_obs
    height_map_topic: rt/heightmap
    step_dt: 0.02
    high_level_decimation: 10
    enable_success_stop: true
    success_distance_threshold: 0.10
    success_yaw_threshold: 0.15
    success_settle_steps: 4
    joint_ids_map: [3, 0, 9, 6, 4, 1, 10, 7, 5, 2, 11, 8]
    stiffness: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
    damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    default_joint_pos: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]
    joint_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    push_action_clip:
      - [-0.5, 1.0]
      - [-1.0, 1.0]
      - [-0.5, 0.5]
