# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import logging
import torch
from collections.abc import Sequence
from typing import TYPE_CHECKING

from isaaclab.terrains import TerrainImporter

from MyProject.tasks.manager_based.BiSheTest.config.terrain import AUTO_STAGE_STEPS, STAGE_PRESETS

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnv

logger = logging.getLogger(__name__)


STAGE_ORDER = ("phase0_walk", "phase1_base", "phase2_gap", "phase3_pit", "phase4_obstacle")


def _env_ids_to_tensor(env: ManagerBasedRLEnv, env_ids: Sequence[int] | torch.Tensor) -> torch.Tensor:
    if isinstance(env_ids, torch.Tensor):
        return env_ids.to(device=env.device, dtype=torch.long)
    return torch.as_tensor(list(env_ids), device=env.device, dtype=torch.long)


def _resolve_stage(mode: str, step_counter: int, auto_stage_steps: tuple[int, int, int, int, int]) -> str:
    if mode != "auto":
        if mode not in STAGE_PRESETS:
            raise ValueError(f"Unknown terrain stage mode: {mode}. Expected one of: {list(STAGE_PRESETS.keys())}")
        return mode

    stage_idx = 0
    for idx, threshold in enumerate(auto_stage_steps):
        if step_counter >= threshold:
            stage_idx = idx
    stage_idx = min(stage_idx, len(STAGE_ORDER) - 1)
    return STAGE_ORDER[stage_idx]


def _compute_column_map(terrain_gen_cfg) -> dict[str, list[int]]:
    """Map each sub-terrain key to terrain columns generated by curriculum mode."""
    names = list(terrain_gen_cfg.sub_terrains.keys())
    proportions = [terrain_gen_cfg.sub_terrains[name].proportion for name in names]
    total = sum(proportions)
    if total <= 0.0:
        return {name: [] for name in names}

    cumulative = []
    running = 0.0
    for p in proportions:
        running += p / total
        cumulative.append(running)

    col_map = {name: [] for name in names}
    for col in range(terrain_gen_cfg.num_cols):
        value = col / float(terrain_gen_cfg.num_cols) + 1.0e-3
        idx = 0
        while idx < len(cumulative) - 1 and value >= cumulative[idx]:
            idx += 1
        col_map[names[idx]].append(col)
    return col_map


def stage_terrain_curriculum(
    env: ManagerBasedRLEnv,
    env_ids: Sequence[int],
    mode: str = "auto",
    command_name: str = "target_pose",
    auto_stage_steps: tuple[int, int, int, int, int] = AUTO_STAGE_STEPS,
) -> torch.Tensor:
    """Staged terrain scheduler for gap / pit / obstacle training.

    This term switches the active terrain column set by stage and updates target radius.
    It is called at reset time, before command resampling.
    """
    terrain: TerrainImporter = env.scene.terrain
    if terrain.cfg.terrain_type != "generator" or terrain.cfg.terrain_generator is None:
        return torch.tensor(0.0, device=env.device)

    env_ids_t = _env_ids_to_tensor(env, env_ids)
    if env_ids_t.numel() == 0:
        return torch.tensor(0.0, device=env.device)

    stage_name = _resolve_stage(mode, env.common_step_counter, auto_stage_steps)
    stage_idx = STAGE_ORDER.index(stage_name)
    stage_cfg = STAGE_PRESETS[stage_name]
    if getattr(env, "_bishe_last_stage_name", None) != stage_name:
        logger.info(
            "[BiSheTest] Stage switched to %s at global step %d.",
            stage_name,
            int(env.common_step_counter),
        )
        env._bishe_last_stage_name = stage_name

    # Adjust target sampling radius for this stage.
    cmd_term = env.command_manager.get_term(command_name)
    if hasattr(cmd_term.cfg, "radius_range"):
        cmd_term.cfg.radius_range = tuple(stage_cfg["radius_range"])

    # Restrict terrain columns to stage-specific sub-terrain keys.
    col_map = _compute_column_map(terrain.cfg.terrain_generator)
    allowed_cols = []
    for key in stage_cfg["keys"]:
        allowed_cols.extend(col_map.get(key, []))
    if len(allowed_cols) == 0:
        allowed_cols = list(range(terrain.cfg.terrain_generator.num_cols))
    allowed_cols_t = torch.as_tensor(allowed_cols, device=env.device, dtype=torch.long)

    sampled = torch.randint(0, allowed_cols_t.numel(), (env_ids_t.numel(),), device=env.device)
    terrain.terrain_types[env_ids_t] = allowed_cols_t[sampled]

    # Clamp terrain difficulty level for the stage.
    max_level = max(
        0,
        min(
            terrain.max_terrain_level - 1,
            int(round((terrain.max_terrain_level - 1) * float(stage_cfg["max_level_ratio"]))),
        ),
    )
    terrain.terrain_levels[env_ids_t] = torch.clamp(terrain.terrain_levels[env_ids_t], min=0, max=max_level)
    terrain.env_origins[env_ids_t] = terrain.terrain_origins[terrain.terrain_levels[env_ids_t], terrain.terrain_types[env_ids_t]]

    return torch.tensor(float(stage_idx), device=env.device)


def terrain_levels_position(
    env: ManagerBasedRLEnv,
    env_ids: Sequence[int],
    command_name: str = "target_pose",
    success_threshold: float = 0.5,
    fail_threshold: float = 2.0,
) -> torch.Tensor:
    """Terrain curriculum based on final distance to target."""
    terrain: TerrainImporter = env.scene.terrain
    if terrain.cfg.terrain_type != "generator" or terrain.cfg.terrain_generator is None:
        return torch.tensor(0.0, device=env.device)

    env_ids_t = _env_ids_to_tensor(env, env_ids)
    if env_ids_t.numel() == 0:
        return torch.tensor(0.0, device=env.device)

    command = env.command_manager.get_command(command_name)
    distance_to_target = torch.norm(command[:, :2], dim=1)

    move_up = distance_to_target[env_ids_t] < success_threshold
    move_down = distance_to_target[env_ids_t] > fail_threshold
    move_down = move_down & (~move_up)

    terrain.update_env_origins(env_ids_t, move_up, move_down)
    return torch.mean(terrain.terrain_levels.float())
